---
- name: Docker Compose | Get installed version
  command: docker-compose --version
  ignore_errors: yes
  changed_when: no
  register: docker_compose_installed_version
  tags: docker-compose

- set_fact:
    docker_compose_reinstall: yes
  when: (docker_compose_installed_version is success and (docker_compose_installed_version.stdout.split(" ")[2].strip(",") is version(docker_compose_version, "!=")))
  tags: docker-compose

- block:
    - name: Docker Compose | Download & Install
      get_url:
        url: "{{ docker_compose_url }}"
        dest: "{{ docker_compose_install_path }}"
        checksum: "{{ docker_compose_checksum }}"
        mode: 0755
  when: docker_compose_installed_version is failed or docker_compose_reinstall        
  tags: docker-compose
